# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a_propos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_A_Propos(object):
    def setupUi(self, A_propos):
        A_propos.setObjectName("A_propos")
        A_propos.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(A_propos)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(A_propos)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)

        self.retranslateUi(A_propos)
        QtCore.QMetaObject.connectSlotsByName(A_propos)

    def retranslateUi(self, A_propos):
        _translate = QtCore.QCoreApplication.translate
        A_propos.setWindowTitle(_translate("A_propos", "Dialog"))
        self.textBrowser.setHtml(_translate("A_propos", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Sans\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AIME est un projet qui vise à apporter une aide aux médecins dans leur tâche d\'encodage des actes médicaux. Le projet ne porte pour l\'instant que sur la psychiatrie.</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Développé par l\'équipe AIME de l\'ENSTAb</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Quéré E. , Dard R , Caylus J. , Calvez A. , Baker H.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    A_propos = QtWidgets.QDialog()
    ui = Ui_A_Propos()
    ui.setupUi(A_propos)
    A_propos.show()
    sys.exit(app.exec_())
